import { Demande } from './demande';

export interface User {
  id?: number;              // Optional, generated by backend
  nom: string;
  email: string;
  motDePasse: string;
  role?: string;            // Defaults to "USER" on backend
  demandes?: Demande[];     // Optional, may be included in some API responses
}
